function interface(A0,A,~,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)

 figure('Name','Comparatoare cu reacție',... 
 'Units','normalized',...
 'Color','#DCDCDC',...
 'Position',[.2 .1 .75 .8],...
 'NumberTitle','off');
T=1/f;

Btitle=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.01 0.92 0.35 0.05],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',18,...
 'String','Comparator neinversor cu reacție');

Group1=uibuttongroup('Visible','on',...
'BackgroundColor','#DCDCDC',...
'ForegroundColor','black',...
'Title','Parametrii circuitului',...
'FontSize',12,...
'TitlePosition','centertop',...
'Tag','text',...
'Position',[0.55 0.47 0.2 0.5]);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.85 0.41 0.095],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',10,...
 'String','Tip comparator',...
 'Parent',Group1);

uicontrol('Style','PopupMenu',...
 'Units','normalized',...
 'Position',[0.6 0.89 0.32 0.05],...
 'Value',C1,...
 'String','neinversor|inversor',...
 'Callback','C1=get(gco,''value''),close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.72 0.2 0.1],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','+E',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.55 0.2 0.1],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','-E',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.38 0.2 0.1],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','R1',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.21 0.2 0.1],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','Rp',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.04 0.2 0.1],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','Vref',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.3 0.72 0.2 0.11],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','[V]',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.3 0.55 0.2 0.11],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','[V]',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.3 0.38 0.2 0.11],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','[kΩ]',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.3 0.21 0.2 0.11],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','[kΩ]',...
 'Parent',Group1);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.3 0.04 0.2 0.11],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','[V]',...
 'Parent',Group1);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.74 0.2 0.08],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String',E1,...
 'Callback','E1=str2num(get(gco,''String''));close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)',...
 'Parent',Group1);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.57 0.2 0.08],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String',E2,...
 'Callback','E2=str2num(get(gco,''String''));close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)',...
 'Parent',Group1);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.40 0.2 0.08],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String',R1,...
 'Callback','R1=str2num(get(gco,''String''));close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)',...
 'Parent',Group1);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.23 0.2 0.08],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String',Rp,...
 'Callback','Rp=str2num(get(gco,''String''));close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)',...
 'Parent',Group1);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.08 0.2 0.08],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String',Vref,...
 'Callback','Vref=str2num(get(gco,''String''));close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)',...
 'Parent',Group1);

Group2=uibuttongroup('Visible','on',...
 'BackgroundColor','#DCDCDC',...
 'ForegroundColor','black',...
 'Title','Semnal de intrare',...
 'FontSize',12,...
 'TitlePosition','centertop',...
 'Tag','text',...
 'Position',[0.77 0.47 0.18 0.5]);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.85 0.41 0.095],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',10,...
 'String','Tip semnal',...
 'Parent',Group2);

uicontrol('Style','PopupMenu',...
 'Units','normalized',...
 'Position',[0.52 0.89 0.45 0.05],...
 'Value',C2,...
 'String','sinus|cosinus|triunghiular|dreptunghiular',...
 'Callback','C2=get(gco,''value''),close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)',...
 'Parent',Group2);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.73 0.2 0.1],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','A0',...
 'Parent',Group2);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.75 0.2 0.08],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'Parent',Group2,...
 'String',A0,...
 'Callback','A0=str2num(get(gco,''String''));close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.28 0.73 0.2 0.11],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','[V]',...
 'Parent',Group2);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.57 0.2 0.1],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','A',...
 'Parent',Group2);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.59 0.2 0.08],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'Parent',Group2,...
 'String',A,...
 'Callback','A=str2num(get(gco,''String''));close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.28 0.57 0.2 0.11],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','[V]',...
 'Parent',Group2);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.41 0.2 0.1],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','f',...
 'Parent',Group2);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.43 0.2 0.08],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String',f,...
 'Callback','f=str2num(get(gco,''String''));close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)',...
 'Parent',Group2);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.28 0.41 0.2 0.11],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','[Hz]',...
 'Parent',Group2);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.25 0.2 0.1],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','T',...
 'Parent',Group2);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.27 0.2 0.08],...
 'Backgroundcolor','#4EE2EC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String',T,...
 'Enable','off',...
 'Parent',Group2);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.28 0.25 0.2 0.11],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String','[s]',...
 'Parent',Group2);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.05 0.35 0.15],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',12,...
 'String','Număr perioade',...
 'Parent',Group2);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.7 0.1 0.2 0.08],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',15,...
 'String',N,...
 'Callback','N=str2num(get(gco,''String''));close;interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)',...
 'Parent',Group2);

if (T<0 || f<0 || N<0 || E1<0 || R1<0 || Rp<0)
    close;
   msgbox('Această componentă nu poate fi negativă! Programul va rula cu valoarea absolută!');
   T=abs(T);
   f=abs(f);
   N=abs(N);
   E1=abs(E1);
   R1=abs(R1); 
   pause(3);
   interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3);
  
else
    T=T;
    f=f;
    N=N;
    E1=E1;
    R1=R1;
    Rp=Rp;
end

t=0:T/100:N*T;
nt=length(t);

if (C2==1)
Vi=A0+(A*sin(2*pi*f.*t));
end
if (C2==2)
Vi=A0+(A*cos(2*pi*f.*t));
end
if (C2==3)
Vi=A0+(A*sawtooth(2*pi*f.*t,0.5));
end
if (C2==4)
Vi=A0+(A*sign(sin(2*pi*f.*t)));
end

 if (C1==1)
     
 Vps=(Vref*((R1+Rp)/Rp))-((R1/Rp)*E2);
 Vpj=(Vref*((R1+Rp)/Rp))-((R1/Rp)*E1);
 
 img1=imread('comp_neinv.png');
 subplot('Position',[0.04 0.63 0.29 0.29]);
 imshow(img1);
 
 Vpsg=zeros(1,nt);
 for i=1:nt
     Vpsg(i)=Vps;
 end
 
  Vpjg=zeros(1,nt);
 for i=1:nt
     Vpjg(i)=Vpj;
 end
 
 Vp=Vps;
Vo=zeros(1,nt);
 for k=1:nt
 Vo(k)=E2;
 if Vi(k)>Vp
 Vo(k)=E1;
 Vp=Vpj;
 elseif Vi(k)<Vp
 Vo(k)=E2;
 Vp=Vps;
 end
 end
 end

 if (C1==2)
     
 Vps=(Vref*(Rp/(R1+Rp)))+((R1/(R1+Rp))*E1);
 Vpj=(Vref*(Rp/(R1+Rp)))+((R1/(R1+Rp))*E2);
 
 img1=imread('comp_inv.png');
 subplot('Position',[0.04 0.63 0.29 0.29]);
 imshow(img1);
 set(Btitle,'String','Comparator inversor cu reacție');
 
 Vpsg=zeros(1,nt);
 for i=1:nt
     Vpsg(i)=Vps;
 end
 
  Vpjg=zeros(1,nt);
 for i=1:nt
     Vpjg(i)=Vpj;
 end
 
  Vp=Vps;
Vo=zeros(1,nt);
 for k=1:nt
 Vo(k)=E2;
 if Vi(k)>Vp
 Vo(k)=E2;
 Vp=Vpj;
 elseif Vi(k)<Vp
 Vo(k)=E1;
 Vp=Vps;
 end
 end
 end

     for k=1:nt
     if Vo(k)>E1
     Vo(k)=E1;
     elseif Vo(k)<E2
     Vo(k)=E2;
     end
     end

Group3=uibuttongroup('Visible','on',...
 'BackgroundColor','#DCDCDC',...
 'ForegroundColor','black',...
 'Title','Tensiunile de prag',...
 'FontSize',12,...
 'TitlePosition','centertop',...
 'Tag','text',...
 'Position',[0.38 0.82 0.15 0.15]);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.56 0.35 0.4],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',14,...
 'String','Vp-sus',...
 'Parent',Group3);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.51 0.56 0.35 0.4],...
 'Backgroundcolor','#4EE2EC',...
 'Foregroundcolor','black',...
 'FontSize',13,...
 'String',Vps,...
 'Enable','off',...
 'Parent',Group3);

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.12 0.35 0.4],...
 'Backgroundcolor','#DCDCDC',...
 'Foregroundcolor','black',...
 'FontSize',14,...
 'String','Vp-jos',...
 'Parent',Group3);

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.51 0.12 0.35 0.4],...
 'Backgroundcolor','#4EE2EC',...
 'Foregroundcolor','black',...
 'FontSize',13,...
 'String',Vpj,...
 'Enable','off',...
 'Parent',Group3);

Group4=uibuttongroup('Visible','on',...
 'BackgroundColor','#DCDCDC',...
 'ForegroundColor','black',...
 'Title','Vizualizare semnale',...
 'FontSize',12,...
 'TitlePosition','centertop',...
 'Tag','Checkbox',...
 'Position',[0.38 0.64 0.15 0.15]);

uicontrol('Style','Checkbox',...
 'Units','normalized',...
 'String','Tensiune de ieșire',...
 'BackgroundColor','#DCDCDC',...
 'FontSize',10,...
 'Position', [0.12 .7 .8 .22],...
 'Value',x1,...
 'Parent',Group4,...
 'Callback','x1=get(gco,''Value''),close,interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)');

uicontrol('Style','Checkbox',...
 'Units','normalized',...
 'String','Tensiune de intrare',...
 'BackgroundColor','#DCDCDC',...
 'FontSize',10,...
 'Position', [0.12 .4 .8 .22],...
 'Value',x2,...
 'Parent',Group4,...
 'Callback','x2=get(gco,''Value''),close,interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)');

uicontrol('Style','Checkbox',...
 'Units','normalized',...
 'String','Tensiunele de prag',...
 'BackgroundColor','#DCDCDC',...
 'FontSize',10,...
 'Position', [0.12 .1 .8 .22],...
 'Value',x3,...
 'Parent',Group4,...
 'Callback','x3=get(gco,''Value''),close,interface(A0,A,T,f,N,C1,C2,E1,E2,R1,Rp,Vref,Vps,Vpj,x1,x2,x3)');

subplot('Position',[0.08 0.2 0.4 0.35]);
g1=plot(t,Vo,'-r','LineWidth',2);
grid on;
hold on;
g2=plot(t,Vi,'-b','LineWidth',2);
grid on;
hold on;
g3=plot(t,Vpsg,':g',t,Vpjg,':g','LineWidth',2);
grid on;
hold on;
title('Tensiuni');
xlabel('timp [s]');
ylabel('amplitudine [V]','color','k');
legend('Vo','Vi','Vp');

subplot('Position',[0.65 0.1 0.25 0.3]);
cla;
plot(Vi,Vo,'-r','LineWidth',1);
grid on;
text(Vps,0,num2str(Vps));
text(Vpj,0,num2str(Vpj));
title('Histereza');
xlabel('Vi [V]');
ylabel('Vo [V]');
ylim([E2-5 E1+5]);
axh = gca; 
color = 'k'; 
linestyle = '-'; 
line(get(axh,'XLim'), [0 0], 'Color', color, 'LineStyle', linestyle);
line([0 0], get(axh,'YLim'), 'Color', color, 'LineStyle', linestyle);

if(x1==1)
    set(g1,'Visible','on');
else 
    set(g1,'Visible','off');
end
if(x2==1)
    set(g2,'Visible','on');
else 
    set(g2,'Visible','off');
end
if(x3==1)
    set(g3,'Visible','on');
else
    set(g3,'Visible','off');
end

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.11 0.03 0.1 0.07],...
'Backgroundcolor','#F8F8FF',...
'Foregroundcolor','black',...
'FontSize',18,...
'String','CLOSE',...
'Callback','close');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.35 0.03 0.1 0.07],...
'Backgroundcolor','#F8F8FF',...
'Foregroundcolor','black',...
'FontSize',18,...
'String','RESET',...
'Callback','Reset=str2num(get(gco,''String''));close;interface(0,10,1,50,3,1,1,12,-12,5,10,0,6,-6,1,1,1)');

if (Rp==0 || f==0 || N==0 || A==0 || T==0 || E1==0 || E2==0)
    close;
    msgbox('Această componentă nu poate fi 0! Rulați din nou programul cu o valoare corespunzătoare!');
end

file1=uimenu('Label','Pentru utilizatori');
 uimenu(file1,'Label','Bibliografie','Callback','open(''Bibliografie.htm'')');
 uimenu(file1,'Label','Contact','Callback','open(''Contact.htm'')');
 
end